name = "deriv"
version = "2.0.0"
description = "Derive functions for your Gleam types"
licences = ["MIT"]
repository = { type = "github", user = "bchase", repo = "deriv" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glance = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
youid = ">= 1.2.0 and < 2.0.0"
tom = ">= 1.1.1 and < 2.0.0"
glance_printer = ">= 2.0.0 and < 3.0.0"
birl = ">= 1.8.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
