name = "deriv"
version = "2.0.0"
description = "Derive functions for your Gleam types"
licences = ["MIT"]
repository = { type = "github", user = "bchase", repo = "deriv" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glance = ">= 5.0.0 and < 6.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
youid = ">= 1.2.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
# glance_printer = ">= 2.0.0 and < 3.0.0"
glance_printer = { git = "git@github.com:bchase/glance_printer.git", ref = "dev" }
birl = ">= 1.8.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
formal = ">= 3.0.0 and < 4.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
# bchase = { path = "../kohort/bchase" }
bchase = { git = "https://github.com/bchase/gleam-bchase", ref = "master" }
radiate = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
filespy = ">= 0.7.0 and < 1.0.0"
# nibble = ">= 1.1.4 and < 2.0.0"
nibble = { git = "git@github.com:bchase/nibble.git", ref = "main" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
